variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Djava.awt.headless=true"
  MAVEN_CI_OPTS: "--fail-at-end -b -s .mvn/settings.xml"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  APP_IMAGE_ID: $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_REPO/proving-ground-webapp:$CI_PIPELINE_ID


stages:
  - build
  - container

build:
  stage: build
  image: maven:3.5-jdk-8
  script:
    - 'export
    - 'mvn $MAVEN_CLI_OPTS install'
    - 'cd proving-ground-gradle-plugin'
    - './gradlew build '
    - 'rm -r .m2/repository/de/qaware/pg'
  cache:
    paths:
      - .m2/repository
      - proving-ground-gradle-plugin/.gradle
  artifacts:
     paths:
      - '*/target/*.jar'
      - '*/build/libs/*.jar'

app-container:
  stage: container
  image: docker:latest
  script:
    - 'cp proving-ground-webapp/target/proving-ground-webapp-*.jar container/proving-ground-webapp.jar'
    - 'docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_REPO'
    - 'docker build --pull -t $APP_IMAGE_ID container'
    - 'docker push $APP_IMAGE_ID'

